# Site settings
title: Adamouization Films
email: adamouizationfilms@gmail.com
description: > # ignore newlines until "baseurl:"
   Filmmaker enthusiast from Monaco working as a Data Scientist in London
baseurl: "" # site subpath
url: "https://adamouization.jaamour.com/" # the base hostname & protocol

# Social media profiles
youtube_username: AdamouizationFilms
youtube_f1_username: AdamouizationF1
# facebook_username: Adamouization
twitter_username: Adamouization

# Address information
location: London & Monaco
address1_city: London
address1_country: UK
address2_city: Monte-Carlo
address2_country: Monaco

# Build settings
markdown: kramdown

# Google analytics tracking ID
google_analytics_tracking_id: G-T1JJYDBSDC
