# Site settings
title: Adamouization Films
email: adamouizationfilms@gmail.com
description: > # ignore newlines until "baseurl:"
   Filmmaker enthusiast from Monaco working as a Data Scientist in London
baseurl: "" # site subpath
url: "http://www.adamouization.jaamour.com" # the base hostname & protocol

# Social media profiles
youtube_username: AdamouizationFilms
facebook_username: Adamouization
twitter_username: Adamouization
instagram_username: adamouization

# Address information
location: London & Monaco
address1_city: London
address1_country: United Kingdom
address2_city: Monaco
address2_country: Monte-Carlo

# Build settings
markdown: kramdown

# Google analytics tracking ID
google_analytics_tracking_id: UA-116916521-2
