# Site settings
title: AdamouizationFilms
email: adamouizationfilms@gmail.com
description: > # ignore newlines until "baseurl:"
  Filmmaker
baseurl: "" # site subpath
url: "http://http://www.adamouization.jaamour.com" # the base hostname & protocol

# Social media profiles
youtube_username: AdamouizationFilms
facebook_username: AdamouizationFilms
twitter_username: Adamouization
instagram_username: adamouization
vine_username: Adamouization

# Address information
address1_city: Monaco
address1_country: Monte-Carlo
address2_city: Bath
address2_country: United Kingdom

# Build settings
markdown: kramdown
