# Site settings
title: AdamouizationFilms
email: adamouizationfilms@gmail.com
description: > # ignore newlines until "baseurl:"
   Filmmaker enthusiast from Monaco studying a Masters in Artificial Intelligence at the University of St Andrews
baseurl: "" # site subpath
url: "http://www.adamouization.jaamour.com" # the base hostname & protocol

# Social media profiles
youtube_username: AdamouizationFilms
facebook_username: Adamouization
twitter_username: Adamouization
instagram_username: adamouization

# Address information
location: Monaco & St Andrews
address1_city: Monaco
address1_country: Monte-Carlo
address2_city: St Andrews
address2_country: Scotland

# Build settings
markdown: kramdown

# Google analytics tracking ID
google_analytics_tracking_id: UA-116916521-2
